### ISSUE TITLE
enable S3 access directly with dask

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-pycommons#23]
The problem is using a custom endpoint and getting `dask` to forward properly the connection params to `s3fs`.

- [x] open an issue on dask
- [ ] once solved, fix our code: everywhere we read/upload.

**Comment by mromanello** [comment]
I've set up a public bucket (`impresso-public`) for testing purposes, (this way we exclude that it's an authorization issue) and it still doesn't work. 

I've found a similar issue in the `dask` repo, closed because of lack of a minimum reproducible example [issue \#1960: Trouble connecting to S3](https://github.com/dask/dask/issues/1960). I've asked to reopen it, let's see.

## Example

- s3 host: `os.zhdk.cloud.switch.ch`
- bucket (`acl-public`): `impresso-public` 
- bucket contents: two JSON lines files (`'impresso-public/GDL-1799.jsonl', 'impresso-public/NZZ-1780.jsonl'`)

```python
import dask.bag as db
b = db.read_text(
    's3://impresso-public/*jsonl', 
    storage_options={'host': 'os.zhdk.cloud.switch.ch', 'anon':True}
)
```

This raises the following exception: 

```python
ValueError: ('No files found', 's3://impresso-public/*')
```

Funnily enough, if I try to connect instead via `s3fs` I can list the bucket's contents

```python
import s3fs

fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url':'https://os.zhdk.cloud.switch.ch'},
    anon=True
)
fs.ls('impresso-public')
>>> ['impresso-public/GDL-1799.jsonl', 'impresso-public/NZZ-1780.jsonl']
```

**Comment by mromanello** [comment]
The following code snippets do work (I was passing the config parameters in the wrong way):

For a **public** bucket:

```python
import dask.bag as db

_storage_options={
    'client_kwargs': {'endpoint_url':'https://os.zhdk.cloud.switch.ch'},
    'anon':True
}

b = db.read_text('s3://impresso-public/*jsonl', storage_options=_storage_options)
b.compute()
```

For a **private** bucket:

```python
import os

my_access = os.environ['SE_ACCESS_KEY']
my_secret = os.environ['SE_SECRET_KEY']

b = db.read_text(
    's3://canonical-rebuilt/NZZ/NZZ-1800.jsonl.bz2',
    storage_options={
        'client_kwargs': {'endpoint_url':'https://os.zhdk.cloud.switch.ch'}, 
        'key':my_access, 'secret':my_secret
     }
)

texts = b.compute()
```

**Comment by simon-clematide** [comment]
Could we have a impresso_pycommons.utils.s3.storage_option property that grabs everything.

**Comment by mromanello** [comment]
TIL that for files to be public in s3 (when uploading via `s3cmd)` you need to say it explicitly -- even if the containing bucket **is** already **public**, e.g.:

```bash
s3cmd put --acl-public  *.bz2 s3://impresso-public/canonical-with-images/
```

**Comment by mromanello** [comment]
(we are doing this all the time now, so it can be closed)
